export const ELEMENT_REGISTRY = [
  {
    type: "heading",
    label: "Heading",
    category: "basic",
    icon: "H1",
    keywords: [
      "title",
      "headline",
      "hero heading",
      "section title",
      "footer heading",
    ],
    defaultContent: {
      text: "Your Heading",
      tag: "h2",
      fontSize: { desktop: 32, tablet: 26, mobile: 22 },
      color: "#111",
      fontWeight: "700",
      fontFamily: "inherit",
      lineHeight: 1.2,
      letterSpacing: 0,
      textTransform: "none",
      linkUrl: "",
      linkTarget: "_self",
    },
  },
  {
    type: "text",
    label: "Rich Text / Paragraph",
    category: "basic",
    icon: "TXT",
    keywords: [
      "paragraph",
      "body text",
      "copy",
      "content",
      "description",
      "blog excerpt",
      "announcement copy",
    ],
    defaultContent: {
      text: "Enter your text here.",
      fontSize: { desktop: 16, tablet: 16, mobile: 15 },
      color: "#444",
      fontFamily: "inherit",
      lineHeight: 1.6,
    },
  },
  {
    type: "text",
    label: "Simple Text",
    category: "basic",
    icon: "TXT",
    keywords: ["paragraph", "simple text", "copy block", "description"],
    defaultContent: {
      text: "Add a short paragraph to explain this section.",
      fontSize: { desktop: 16, tablet: 16, mobile: 15 },
      color: "#475569",
      fontFamily: "inherit",
      lineHeight: 1.6,
    },
  },
  {
    type: "text",
    label: "Caption",
    category: "basic",
    icon: "CAP",
    keywords: ["caption", "eyebrow", "microcopy", "supporting text"],
    defaultContent: {
      text: "Short supporting note",
      fontSize: { desktop: 13, tablet: 13, mobile: 12 },
      color: "#64748b",
      fontFamily: "inherit",
      lineHeight: 1.5,
    },
  },
  {
    type: "image",
    label: "Image",
    category: "media",
    icon: "IMG",
    keywords: [
      "image block",
      "image banner",
      "photo",
      "gallery image",
      "collage",
      "brand image",
    ],
    defaultContent: {
      src: "https://placehold.co/800x400",
      alt: "",
      linkUrl: "",
      linkTarget: "_self",
      objectFit: "cover",
      loading: "lazy",
    },
  },
  {
    type: "image",
    label: "Logo Image",
    category: "media",
    icon: "LOGO",
    keywords: ["logo", "brand mark", "partner logo", "badge image"],
    defaultContent: {
      src: "https://placehold.co/320x120?text=Logo",
      alt: "Brand logo",
      linkUrl: "",
      linkTarget: "_self",
      objectFit: "contain",
      loading: "lazy",
      widthPx: { desktop: 220, tablet: 180, mobile: 160 },
      heightPx: { desktop: 120, tablet: 100, mobile: 88 },
    },
  },
  {
    type: "button",
    label: "Button / CTA",
    category: "basic",
    icon: "CTA",
    keywords: [
      "call to action",
      "buy now",
      "shop now",
      "quick add",
      "add to cart button",
      "link button",
    ],
    defaultContent: {
      text: "Click Here",
      url: "#",
      target: "_self",
      style: "filled",
      size: "medium",
      backgroundColor: "#111",
      textColor: "#fff",
      borderColor: "#111",
      hoverBackgroundColor: "#333",
      hoverTextColor: "#fff",
      icon: null,
      iconPosition: "left",
    },
  },
  {
    type: "divider",
    label: "Divider",
    category: "basic",
    icon: "---",
    keywords: ["separator", "rule", "line", "section break"],
    defaultContent: {
      style: "solid",
      color: "#e5e7eb",
      thickness: 1,
      width: 100,
      alignment: "center",
    },
  },
  {
    type: "spacer",
    label: "Spacer",
    category: "basic",
    icon: "SPC",
    keywords: ["gap", "empty space", "padding spacer"],
    defaultContent: { height: { desktop: 40, tablet: 30, mobile: 20 } },
  },
  {
    type: "icon",
    label: "Icon / Badge",
    category: "basic",
    icon: "ICO",
    keywords: [
      "feature icon",
      "checkmark",
      "trust icon",
      "badge",
      "tag",
    ],
    defaultContent: {
      icon: "star",
      size: { desktop: 40, tablet: 36, mobile: 32 },
      color: "#111",
      linkUrl: "",
    },
  },
  {
    type: "social_icons",
    label: "Social / Payment Icons",
    category: "basic",
    icon: "SOC",
    keywords: [
      "social links",
      "social media",
      "payment icons",
      "trust badges",
      "secure checkout",
      "press logos",
      "footer social",
    ],
    defaultContent: {
      icons: [
        { platform: "instagram", url: "#" },
        { platform: "facebook", url: "#" },
      ],
      iconSize: 24,
      iconColor: "#111",
      iconStyle: "logo",
      gap: 12,
      alignment: "center",
    },
  },
  {
    type: "video",
    label: "Video / Background Video",
    category: "media",
    icon: "VID",
    keywords: [
      "video banner",
      "hero video",
      "youtube",
      "vimeo",
      "mp4",
      "media block",
    ],
    defaultContent: {
      videoType: "youtube",
      url: "",
      autoplay: false,
      loop: false,
      muted: false,
      controls: true,
      aspectRatio: "16:9",
      posterImage: "",
    },
  },
  {
    type: "video",
    label: "Video Embed",
    category: "media",
    icon: "PLAY",
    keywords: ["video embed", "youtube embed", "vimeo embed", "promo video"],
    defaultContent: {
      videoType: "youtube",
      url: "",
      autoplay: false,
      loop: false,
      muted: false,
      controls: true,
      aspectRatio: "16:9",
      posterImage: "",
    },
  },
  {
    type: "map",
    label: "Map / Store Locator",
    category: "media",
    icon: "MAP",
    keywords: [
      "google map",
      "location",
      "address",
      "contact map",
      "store locator",
    ],
    defaultContent: {
      query: "New York, NY",
      zoom: 12,
      height: { desktop: 420, tablet: 360, mobile: 300 },
    },
  },
  {
    type: "slider",
    label: "Slideshow / Carousel",
    category: "media",
    icon: "SLD",
    keywords: [
      "hero slider",
      "slideshow",
      "carousel",
      "banner slider",
      "image slider",
      "gallery slider",
    ],
    defaultContent: {
      slides: [],
      autoplay: true,
      autoplaySpeed: 5000,
      showArrows: true,
      showDots: true,
      height: { desktop: 500, tablet: 400, mobile: 300 },
      transition: "slide",
    },
  },
  {
    type: "product_card",
    label: "Featured Product",
    category: "commerce",
    icon: "PROD",
    keywords: [
      "product showcase",
      "single product",
      "buy now",
      "quick add",
      "product block",
      "product media",
    ],
    defaultContent: {
      productHandle: "",
      showPrice: true,
      showTitle: true,
      showVendor: false,
      showRating: false,
      showAddToCart: true,
      imageRatio: "square",
      layout: "vertical",
    },
  },
  {
    type: "product_grid",
    label: "Product Grid / Recommendations",
    category: "commerce",
    icon: "GRID",
    keywords: [
      "featured products",
      "product recommendations",
      "also bought",
      "related products",
      "recently viewed",
      "cross sell",
      "upsell",
    ],
    defaultContent: {
      source: "collection",
      collectionId: "",
      productIds: [],
      tag: "",
      columns: { desktop: 3, tablet: 2, mobile: 1 },
      limit: 8,
      showPagination: false,
      sortBy: "best-selling",
    },
  },
  {
    type: "collection",
    label: "Featured Collection / Grid",
    category: "commerce",
    icon: "COL",
    keywords: [
      "collection list",
      "collection grid",
      "featured collection",
      "collection banner",
      "shop categories",
    ],
    defaultContent: {
      collectionHandle: "",
      columns: { desktop: 3, tablet: 2, mobile: 1 },
      showTitle: true,
      showProductCount: false,
      imageRatio: "square",
      limit: 6,
    },
  },
  {
    type: "testimonial",
    label: "Testimonials / Reviews",
    category: "social",
    icon: "REV",
    keywords: [
      "social proof",
      "customer reviews",
      "ratings",
      "ugc",
      "press quotes",
      "review cards",
    ],
    defaultContent: {
      items: [
        {
          id: "1",
          quote: "Amazing product!",
          author: "Jane D.",
          role: "Customer",
          avatar: "",
          rating: 5,
        },
      ],
      layout: "grid",
      columns: { desktop: 3, tablet: 2, mobile: 1 },
      showRating: true,
      showAvatar: false,
    },
  },
  {
    type: "countdown",
    label: "Countdown Timer",
    category: "interactive",
    icon: "TMR",
    keywords: [
      "promo timer",
      "sale timer",
      "launch countdown",
      "announcement timer",
    ],
    defaultContent: {
      targetDate: new Date(Date.now() + 7 * 86400000).toISOString(),
      timezone: "UTC",
      showDays: true,
      showHours: true,
      showMinutes: true,
      showSeconds: true,
      labelStyle: "below",
      numberColor: "#111",
      labelColor: "#888",
      separatorColor: "#ddd",
      expiredText: "This offer has ended",
      redirectUrl: "",
    },
  },
  {
    type: "accordion",
    label: "FAQ / Accordion",
    category: "interactive",
    icon: "FAQ",
    keywords: [
      "questions",
      "collapsible content",
      "support answers",
      "help center",
    ],
    defaultContent: {
      items: [
        {
          id: "1",
          question: "What is your return policy?",
          answer: "We offer a 30-day return policy on all items.",
        },
      ],
      allowMultiple: false,
      defaultOpen: null,
      iconType: "plus",
      borderColor: "#e5e7eb",
      headingColor: "#111",
      contentColor: "#555",
    },
  },
  {
    type: "tabs",
    label: "Tabs / Product Tabs",
    category: "interactive",
    icon: "TAB",
    keywords: [
      "tabbed content",
      "product tabs",
      "description tabs",
      "shipping tabs",
      "review tabs",
    ],
    defaultContent: {
      tabs: [
        { id: "1", label: "Tab 1", content: "<p>Content for Tab 1</p>" },
        { id: "2", label: "Tab 2", content: "<p>Content for Tab 2</p>" },
      ],
      activeColor: "#111",
      inactiveColor: "#888",
      tabStyle: "underline",
      alignment: "left",
    },
  },
  {
    type: "form",
    label: "Contact / Newsletter Form",
    category: "interactive",
    icon: "FORM",
    keywords: [
      "email signup",
      "newsletter",
      "contact form",
      "lead capture",
      "popup form",
      "discount form",
    ],
    defaultContent: {
      fields: [
        {
          id: "1",
          type: "text",
          label: "Name",
          placeholder: "Your name",
          required: true,
          options: [],
        },
        {
          id: "2",
          type: "email",
          label: "Email",
          placeholder: "your@email.com",
          required: true,
          options: [],
        },
      ],
      submitText: "Submit",
      successMessage: "Thank you!",
      emailRecipient: "",
      backgroundColor: "transparent",
      inputBorderColor: "#d1d5db",
      buttonColor: "#111",
      buttonTextColor: "#fff",
    },
  },
  {
    type: "html",
    label: "HTML / Embed",
    category: "advanced",
    icon: "HTML",
    keywords: [
      "custom html",
      "embed code",
      "ugc feed",
      "instagram feed",
      "review widget",
      "judge.me",
      "yotpo",
      "loox",
      "chat widget",
      "cookie banner",
    ],
    defaultContent: { html: "" },
  },
  {
    type: "liquid",
    label: "Custom Liquid / App Block",
    category: "advanced",
    icon: "LIQ",
    keywords: [
      "theme section",
      "search bar",
      "predictive search",
      "breadcrumbs",
      "mega menu",
      "sticky header",
      "wishlist",
      "compare products",
      "language switcher",
      "currency switcher",
      "cart drawer",
      "loyalty",
      "rewards",
      "app block",
    ],
    defaultContent: { liquid: "" },
  },
] as const;

export const ELEMENT_CATEGORIES = [
  { key: "basic", label: "Basic" },
  { key: "media", label: "Media" },
  { key: "commerce", label: "Commerce" },
  { key: "social", label: "Social Proof" },
  { key: "interactive", label: "Interactive" },
  { key: "advanced", label: "Advanced" },
] as const;
