export const ELEMENT_REGISTRY = [
  // Basic
  {
    type: "heading",
    label: "Heading",
    category: "basic",
    icon: "H1",
    defaultContent: {
      text: "Your Heading",
      tag: "h2",
      fontSize: { desktop: 32, tablet: 26, mobile: 22 },
      color: "#111",
      fontWeight: "700",
      fontFamily: "inherit",
      lineHeight: 1.2,
      letterSpacing: 0,
      textTransform: "none",
      linkUrl: "",
      linkTarget: "_self",
    },
  },
  {
    type: "text",
    label: "Text",
    category: "basic",
    icon: "T",
    defaultContent: {
      html: "<p>Enter your text here. Click to edit.</p>",
      fontSize: { desktop: 16, tablet: 16, mobile: 15 },
      color: "#444",
      fontFamily: "inherit",
      lineHeight: 1.6,
    },
  },
  {
    type: "image",
    label: "Image",
    category: "basic",
    icon: "IMG",
    defaultContent: {
      src: "https://placehold.co/800x400",
      alt: "",
      linkUrl: "",
      linkTarget: "_self",
      objectFit: "cover",
      loading: "lazy",
    },
  },
  {
    type: "button",
    label: "Button",
    category: "basic",
    icon: "BTN",
    defaultContent: {
      text: "Click Here",
      url: "#",
      target: "_self",
      style: "filled",
      size: "medium",
      backgroundColor: "#111",
      textColor: "#fff",
      borderColor: "#111",
      hoverBackgroundColor: "#333",
      hoverTextColor: "#fff",
      icon: null,
      iconPosition: "left",
    },
  },
  {
    type: "divider",
    label: "Divider",
    category: "basic",
    icon: "—",
    defaultContent: {
      style: "solid",
      color: "#e5e7eb",
      thickness: 1,
      width: 100,
      alignment: "center",
    },
  },
  {
    type: "spacer",
    label: "Spacer",
    category: "basic",
    icon: "↕",
    defaultContent: { height: { desktop: 40, tablet: 30, mobile: 20 } },
  },
  {
    type: "icon",
    label: "Icon",
    category: "basic",
    icon: "★",
    defaultContent: {
      icon: "star",
      size: { desktop: 40, tablet: 36, mobile: 32 },
      color: "#111",
      linkUrl: "",
    },
  },
  // Media
  {
    type: "video",
    label: "Video",
    category: "media",
    icon: "▶",
    defaultContent: {
      videoType: "youtube",
      url: "",
      autoplay: false,
      loop: false,
      muted: false,
      controls: true,
      aspectRatio: "16:9",
      posterImage: "",
    },
  },
  {
    type: "map",
    label: "Map",
    category: "media",
    icon: "MAP",
    defaultContent: {
      query: "New York, NY",
      zoom: 12,
      height: { desktop: 420, tablet: 360, mobile: 300 },
    },
  },
  {
    type: "slider",
    label: "Slider",
    category: "media",
    icon: "◀▶",
    defaultContent: {
      slides: [],
      autoplay: true,
      autoplaySpeed: 5000,
      showArrows: true,
      showDots: true,
      height: { desktop: 500, tablet: 400, mobile: 300 },
      transition: "slide",
    },
  },
  // Commerce
  {
    type: "product_card",
    label: "Product Card",
    category: "commerce",
    icon: "🛍",
    defaultContent: {
      productHandle: "",
      showPrice: true,
      showTitle: true,
      showVendor: false,
      showRating: false,
      showAddToCart: true,
      imageRatio: "square",
      layout: "vertical",
    },
  },
  {
    type: "product_grid",
    label: "Product Grid",
    category: "commerce",
    icon: "⊞",
    defaultContent: {
      source: "collection",
      collectionId: "",
      productIds: [],
      tag: "",
      columns: { desktop: 3, tablet: 2, mobile: 1 },
      limit: 8,
      showPagination: false,
      sortBy: "best-selling",
    },
  },
  {
    type: "collection",
    label: "Collection",
    category: "commerce",
    icon: "🗂",
    defaultContent: {
      collectionHandle: "",
      columns: { desktop: 3, tablet: 2, mobile: 1 },
      showTitle: true,
      showProductCount: false,
      imageRatio: "square",
      limit: 6,
    },
  },
  // Social proof
  {
    type: "testimonial",
    label: "Testimonials",
    category: "social",
    icon: "❝",
    defaultContent: {
      items: [
        {
          id: "1",
          quote: "Amazing product!",
          author: "Jane D.",
          role: "Customer",
          avatar: "",
          rating: 5,
        },
      ],
      layout: "grid",
      columns: { desktop: 3, tablet: 2, mobile: 1 },
      showRating: true,
      showAvatar: false,
    },
  },
  // Interactive
  {
    type: "countdown",
    label: "Countdown",
    category: "interactive",
    icon: "⏱",
    defaultContent: {
      targetDate: new Date(Date.now() + 7 * 86400000).toISOString(),
      timezone: "UTC",
      showDays: true,
      showHours: true,
      showMinutes: true,
      showSeconds: true,
      labelStyle: "below",
      numberColor: "#111",
      labelColor: "#888",
      separatorColor: "#ddd",
      expiredText: "This offer has ended",
      redirectUrl: "",
    },
  },
  {
    type: "accordion",
    label: "FAQ / Accordion",
    category: "interactive",
    icon: "≡",
    defaultContent: {
      items: [
        {
          id: "1",
          question: "What is your return policy?",
          answer: "We offer a 30-day return policy on all items.",
        },
      ],
      allowMultiple: false,
      defaultOpen: null,
      iconType: "plus",
      borderColor: "#e5e7eb",
      headingColor: "#111",
      contentColor: "#555",
    },
  },
  {
    type: "tabs",
    label: "Tabs",
    category: "interactive",
    icon: "⊟",
    defaultContent: {
      tabs: [
        { id: "1", label: "Tab 1", content: "<p>Content for Tab 1</p>" },
        { id: "2", label: "Tab 2", content: "<p>Content for Tab 2</p>" },
      ],
      activeColor: "#111",
      inactiveColor: "#888",
      tabStyle: "underline",
      alignment: "left",
    },
  },
  {
    type: "form",
    label: "Form",
    category: "interactive",
    icon: "✉",
    defaultContent: {
      fields: [
        {
          id: "1",
          type: "text",
          label: "Name",
          placeholder: "Your name",
          required: true,
          options: [],
        },
        {
          id: "2",
          type: "email",
          label: "Email",
          placeholder: "your@email.com",
          required: true,
          options: [],
        },
      ],
      submitText: "Submit",
      successMessage: "Thank you!",
      emailRecipient: "",
      backgroundColor: "transparent",
      inputBorderColor: "#d1d5db",
      buttonColor: "#111",
      buttonTextColor: "#fff",
    },
  },
  // Advanced
  {
    type: "html",
    label: "HTML",
    category: "advanced",
    icon: "</>",
    defaultContent: { html: "<!-- Custom HTML -->" },
  },
  {
    type: "liquid",
    label: "Liquid",
    category: "advanced",
    icon: "{%}",
    defaultContent: { liquid: "{% comment %} Custom Liquid {% endcomment %}" },
  },
  {
    type: "social_icons",
    label: "Social Icons",
    category: "basic",
    icon: "◎",
    defaultContent: {
      icons: [
        { platform: "instagram", url: "#" },
        { platform: "facebook", url: "#" },
      ],
      iconSize: 24,
      iconColor: "#111",
      iconStyle: "logo",
      gap: 12,
      alignment: "center",
    },
  },
] as const;

export const ELEMENT_CATEGORIES = [
  { key: "basic", label: "Basic" },
  { key: "media", label: "Media" },
  { key: "commerce", label: "Commerce" },
  { key: "social", label: "Social Proof" },
  { key: "interactive", label: "Interactive" },
  { key: "advanced", label: "Advanced" },
] as const;
