# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e6eac3e30a11b7768751add395d9c3e2"
name = "ShopBuilder - app"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "themes/publish" ]
  uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_themes,read_themes,read_content,write_content,read_products,write_products,read_collection_listings,write_files"

[auth]
redirect_urls = [ "https://example.com/auth/callback" ]
